services:
  - type: web
    name: millat-e-islami
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        generateValue: false
        value: admin1234
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
